site_name: Rust入門

theme:
  name: material
  locale: ja
  features:
    - toc.integrate
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

nav:
  - 序文: index.md
  - データ型: data_type.md

markdown_extensions:
  - admonition
  - fontawesome_markdown
  - codehilite
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"

repo_url: https://github.com/yoshiyasu1111/introduction-rust
repo_name: yoshiyasu1111/introduction-rust

extra:
  analytics:
    provider: google
    property: G-Q10LRY3ME7
